<a href="https://colab.research.google.com/github/rajgit-123/python-repo/blob/main/day5of45_python_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#NUMPY#

In [11]:
#Calculate BMI using list
height=[1.70,1.59,1.51,1.73,1.92]
weight=[65.9,58.8,66.8,83.4,68.7]
#BMI=weight/height **2   #TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

#print(BMI)

#BMI Using numpy
import numpy as np
np_height=np.array(height)
np_weight=np.array(weight)
print(np_height)
print(np_weight)

BMI=np_weight/np_height ** 2
print(BMI)
print(BMI[1])
print(BMI>23)
print(BMI[BMI>23])

[1.7  1.59 1.51 1.73 1.92]
[65.9 58.8 66.8 83.4 68.7]
[22.80276817 23.25857363 29.29696066 27.86594941 18.63606771]
23.258573632372133
[False  True  True  True False]
[23.25857363 29.29696066 27.86594941]


In [ ]:
#Numpy main object is the homogeneous and multidimentional array
#Numpy Stands for Numerical Python
#