<a href="https://colab.research.google.com/github/rajgit-123/python-repo/blob/main/day6of45_python_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
l=[1,2,3,4]
n=np.array([1,2,3.9])
print(l)
print(n)

a=np.arange(6)
b=np.arange(12).reshape(4,3)
c=np.arange(24).reshape(2,3,4)
d=np.arange(24).reshape(2,3,2,2)

#print(a)
#print(b)
#print(c)
#print(d)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

[1, 2, 3, 4]
[1.  2.  3.9]
1
2
3
4


In [20]:
#can do the calculations over entire elements on NUMPY
import sys
import numpy as np
l=[1,2,3,4,5,6,7,8,9,10,11,12]
n=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(sys.getsizeof(l))
print(sys.getsizeof(n))

#2D array
np_2d_array=np.array([[1.7,  1.59, 1.51, 1.73, 1.92],[65.9, 58.8, 66.8, 83.4, 68.7]])
print(type(np_2d_array))

print(np_2d_array[0])
print(np_2d_array[0][2])
print(np_2d_array[0,2])
print(np_2d_array[1,:])

152
208
<class 'numpy.ndarray'>
[1.7  1.59 1.51 1.73 1.92]
1.51
1.51
[65.9 58.8 66.8 83.4 68.7]


In [22]:
#Basic statistics
import numpy as np
x=[1,4,8,10,12]
print(np.mean(x))
print(np.median(x))
print(np.std(x))

7.0
8.0
4.0


In [53]:
import numpy as np
print(np.random.randint(10,50,5))

print(np.random.seed(100))

a=np.arange(12).reshape(3,-1)
print(a)

b=np.random.shuffle(a)
print(b)

c=np.random.permutation(a)
print(c)

d=np.random.choice(l)####l should be 1d array
print(d)

e=np.random.choice(l,3)
print(e)

f=np.array(np.random.rand(12)).reshape(3,-1)
print(f)

print(a+f)

[29 46 14 37 13]
None
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
None
[[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]
5
[3 6 3]
[[0.21010774 0.4527399  0.87014264 0.06368104]
 [0.62431189 0.52334774 0.56229626 0.00581719]
 [0.30742321 0.95018431 0.12665424 0.07898787]]
[[ 4.21010774  5.4527399   6.87014264  7.06368104]
 [ 8.62431189  9.52334774 10.56229626 11.00581719]
 [ 0.30742321  1.95018431  2.12665424  3.07898787]]


In [70]:
import pandas as pd
import numpy as np
import os
import kagglehub
path = kagglehub.dataset_download("tmdb/tmdb-movie-metadata")

df =pd.read_csv(path+"/tmdb_5000_movies.csv")
# print(df.head())
# print(df.info())
# print(df.describe())
# print(df.shape)
# print(df.columns  )
# print(df.index)
df.iloc[1,1]
#df.loc[1,'original_title']
df.iloc[1:3,1:3]


Using Colab cache for faster access to the 'tmdb-movie-metadata' dataset.


,genres,homepage
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/
